
export GIT_URL="https://github.com/MrKsey/ss-tls-v2ray"

export SS_URL="https://api.github.com/repos/shadowsocks/shadowsocks-rust/releases"
export SS_VER="latest"

export SIMPLE_TLS_URL="https://api.github.com/repos/IrineSistiana/simple-tls/releases"
export SIMPLE_TLS_VER="latest"

export V2RAY_URL="https://api.github.com/repos/shadowsocks/v2ray-plugin/releases"
export V2RAY_VER="latest"

export USER_AGENT="Mozilla/5.0 (X11; Linux x86_64; rv:77.0) Gecko/20100101 Firefox/77.0"

export CONFIG_PATH="/etc/shadowsocks"

export DEBIAN_FRONTEND=noninteractive \
&& apt-get update && apt-get upgrade -y \
&& apt-get install --no-install-recommends -y ca-certificates tzdata curl wget xz-utils unzip jq subversion moreutils libcap2-bin cron lsof \
&& mkdir /tmp/ss && cd /tmp/ss \
&& export SS_VER=$([ "$SS_VER" != "latest" ] && echo tags/$SS_VER || echo $SS_VER) \
&& wget --no-verbose --no-check-certificate --user-agent="$USER_AGENT" --output-document=/tmp/ss/ss.tar.xz --tries=3 $(\
   curl -s $SS_URL/$SS_VER | grep -o -E 'http.+\w+' | grep -i "$(uname)" | grep -i "gnu" | grep -i -v "sha256" | \
   grep -i -E "$(dpkg --print-architecture | sed "s/amd64/x86_64/g" | sed "s/arm64/aarch64/g" | sed "s/armhf/arm.+eabihf/g")") \
&& tar -xf ss.tar.xz --directory /usr/local/bin \
&& export SIMPLE_TLS_VER=$([ "$SIMPLE_TLS_VER" != "latest" ] && echo tags/$SIMPLE_TLS_VER || echo $SIMPLE_TLS_VER) \
&& wget --no-verbose --no-check-certificate --user-agent="$USER_AGENT" --output-document=/tmp/ss/simple_tls.zip --tries=3 $(\
   curl -s $SIMPLE_TLS_URL/$SIMPLE_TLS_VER | grep -o -E 'http.+\w+' | grep -i "$(uname)" | \
   grep -i -E "$(dpkg --print-architecture | sed "s/armhf/arm-7/g")") \
&& unzip -x -o simple_tls.zip simple-tls -d /usr/local/bin \
&& export V2RAY_VER=$([ "$V2RAY_VER" != "latest" ] && echo tags/$V2RAY_VER || echo $V2RAY_VER) \
&& wget --no-verbose --no-check-certificate --user-agent="$USER_AGENT" --output-document=/tmp/ss/v2ray.tar.gz --tries=3 $(\
   curl -s $V2RAY_URL/$V2RAY_VER | grep -o -E 'http.+\w+' | grep -i "$(uname)" | \
   grep -i -E "$(dpkg --print-architecture | sed "s/armhf/-arm-/g")") \
&& tar -xf v2ray.tar.gz --directory /usr/local/bin && ln -f -s /usr/local/bin/v2ray-* /usr/local/bin/v2ray \
&& chown -R root:root /usr/local/bin && chmod -R a+x /usr/local/bin \
&& cd / && rm -rf /tmp/ss \
&& apt-get purge -y -q --auto-remove \
&& apt-get clean \
&& touch /var/log/cron.log \
&& ln -sf /proc/1/fd/1 /var/log/cron.log

VOLUME [ "$CONFIG_PATH" ]

ENTRYPOINT ["/start.sh"]
